### ISSUE TITLE
require proposer to deposit ETH / deal with ETH for canceled proposals

### ISSUE THREAD

**Issue by nmushegian** [dapphub/ds-group#5]
Right now a queue of proposals all use the same pool of ETH, so if you want a paid action you have to wait until yours is in line before depositing, and also hope that it is not triggered without your deposit

**Comment by dbrock** [comment]
I don't understand this... what is a paid action?

**Comment by nmushegian** [comment]
An action with value > 0. Right now if I deposit 10 ETH with my proposal for action 11, action 10 might take it, if previous proposers didn't give the contract enough ETH

**Comment by dbrock** [comment]
Hmm... I would think the ETH would come in separately, and the proposal be precisely how to distribute this previously collected ETH. If I already own the ETH, why don't I just send it to the recipient directly?

**Comment by dbrock** [comment]
This requirement seems too obscure. What about ERC20 tokens?
