### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by kennyrowe** [dapphub/ds-group#7]
- `~$ ds-group ls @mkrgroup` example listed three times
- Add documentation of constructor
  - example constructor `dapp create DSGroup '[4f26ffbe5f04ed43630fdc30a87638d53d0b0876,855Be87Fe5DDeA2761dbD97f1a4e857Aa00a15FD,c9107bd75a6971d9beaba390a28ab9bb30adc9bc,6ea073f4de9cd42955539033091ae587c06a882c,dB33dFD3D61308C33C63209845DaD3e6bfb2c674,61Bf84D5aB026F58c873F86Ff0DFcA82b55733Ae]' 2 86400`
  - Define constructor arguments

**Comment by ghost** [comment]
will do
